/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fractalzoomer.gui;

import java.awt.Dimension;
import javax.swing.JEditorPane;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author kaloch
 */
public class UserFormulasHelpDialog {
    
    public UserFormulasHelpDialog(MainPanel main_panel, JScrollPane scroll_pane) {
        JEditorPane textArea = new JEditorPane();

        textArea.setEditable(false);
        textArea.setContentType("text/html");
        textArea.setPreferredSize(new Dimension(600, 400));

        JScrollPane scroll_pane_2 = new JScrollPane(textArea);
        scroll_pane_2.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

        String overview = "<font size='5' face='arial' color='blue'><center><b><u>User Formulas</u></b></center></font><br><br>"
                + "<font  face='arial'><font color='blue'><center><b><u>Variables</u></b></center></font><br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>z</b></font>: current sequence point.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>c</b></font>: plane point.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>s</b></font>: starting sequence point.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>p</b></font>: previous sequence point.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>pp</b></font>: second to previous sequence point.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>n</b></font>: current iteration.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>maxn</b></font>: current maximum iterations.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>bail</b></font>: current bailout.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>cbail</b></font>: convergent bailout.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>center</b></font>: current center.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>size</b></font>: current size.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>sizei</b></font>: current image size (size / sizei will yield the pixel size).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v1</b></font>: placeholder variable 1.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v2</b></font>: placeholder variable 2.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v3</b></font>: placeholder variable 3.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v4</b></font>: placeholder variable 4.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v5</b></font>: placeholder variable 5.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v6</b></font>: placeholder variable 6.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v7</b></font>: placeholder variable 7.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v8</b></font>: placeholder variable 8.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v9</b></font>: placeholder variable 9.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v10</b></font>: placeholder variable 10.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v11</b></font>: placeholder variable 11.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v12</b></font>: placeholder variable 12.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v13</b></font>: placeholder variable 13.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v14</b></font>: placeholder variable 14.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v15</b></font>: placeholder variable 15.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v16</b></font>: placeholder variable 16.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v17</b></font>: placeholder variable 17.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v18</b></font>: placeholder variable 18.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v19</b></font>: placeholder variable 19.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>v20</b></font>: placeholder variable 20.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>point</b></font>: a value that can be picked by the user.<br><br>"
                + "All the placeholder variables are meant to be used inside<br>"
                + "the UserDefinedFunctions.java file, in order to store some temporary values<br>"
                + "that can be used later on, at a user defined out-coloring or in-coloring method.<br>"
                + "These variables are focused on experienced users that might have some<br>"
                + "computer science background.<br>"
                + "You must use the mutable versions of the complex functions or use<br>"
                + "the assign function on these variables, or else the value that you want to save<br>"
                + "will be lost. For instance when you want to set the value of a variable do not use<br>"
                + "<b>v = new Complex(1, 2)</b> but you should use <b>v.assign(new Complex(1, 2))</b><br>"
                + "Initially these variables are set to 0.<br><br>"
                + "Consider the following scenario, you call <b>m1(z, c, v1)</b> and inside <br>"
                + "the body of m1, defined in UserDefinedFunctions.java you set a value to the<br>"
                + "3rd argument of the m1 function based on some condition, defined by you.<br>"
                + "When the iteration terminates the out-coloring or in-coloring method is<br>"
                + "called, for example <b>cos(3*v1)</b>, and uppon this point the value of <b>v1</b> that<br>"
                + "was set during the iteration step will be used. You can have a similar result<br>"
                + "if you use it inside a user bailout formula that calls a function defined in<br>"
                + "UserDefinedFunctions.java<br><br><br>"
                + "<font  face='arial'><font color='blue'><center><b><u>Operations/Symbols</u></b></center></font><br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>+</b></font>: addition.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>-</b></font>: subtraction.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>*</b></font>: multiplication.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>/</b></font>: division.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>%</b></font>: remainder.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>^</b></font>: exponentiation.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>(</b></font>: left parenthesis.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>)</b></font>: right parenthesis.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>,</b></font>: comma.<br><br><br>"
                + "<font  face='arial'><font color='blue'><center><b><u>Constants</u></b></center></font><br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>pi</b></font>: 3.141592653589793.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>e</b></font>: 2.718281828459045.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>phi</b></font>: 1.618033988749895.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>c10 (Champernowne's)</b></font>: 0.1234567891011121314.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>alpha (Feigenbaum's)</b></font>: 2.5029078750958928.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>delta (Feigenbaum's)</b></font>: 4.669201609102990.<br><br><br>"
                + "<font  face='arial'><font color='blue'><center><b><u>Complex Numbers</u></b></center></font><br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>a + bi</b></font>: a = Real, b = Imaginary.<br><br><br>"
                
                + "<font  face='arial'><font color='blue'><center><b><u>Trigonometric Functions: f(z)</u></b></center></font><br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>sin</b></font>: sine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>cos</b></font>: cosine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>tan</b></font>: tangent function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>cot</b></font>: cotangent function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>sec</b></font>: secant function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>csc</b></font>: cosecant function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>sinh</b></font>: hyperbolic sine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>cosh</b></font>: hyperbolic cosine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>tanh</b></font>: hyperbolic tangent function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>coth</b></font>: hyperbolic cotangent function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>sech</b></font>: hyperbolic secant function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>csch</b></font>: hyperbolic cosecant function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>asin</b></font>: arc sine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>acos</b></font>: arc cosine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>atan</b></font>: arc tangent function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>acot</b></font>: arc cotangent function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>asec</b></font>: arc secant function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>acsc</b></font>: arc cosecant function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>asinh</b></font>: hyperbolic arc sine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>acosh</b></font>: hyperbolic arc cosine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>atanh</b></font>: hyperbolic arc tangent function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>acoth</b></font>: hyperbolic arc cotangent function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>asech</b></font>: hyperbolic arc secant function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>acsch</b></font>: hyperbolic arc cosecant function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>vsin</b></font>: versine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>vcos</b></font>: vercosine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>cvsin</b></font>: coversine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>cvcos</b></font>: covercosine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>hvsin</b></font>: haversine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>hvcos</b></font>: havercosine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>hcvsin</b></font>: hacoversine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>hcvcos</b></font>: hacovercosine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>exsec</b></font>: exsecant function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>excsc</b></font>: excosecant function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>avsin</b></font>: arc versine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>avcos</b></font>: arc vercosine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>acvsin</b></font>: arc coversine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>acvcos</b></font>: arc covercosine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>ahvsin</b></font>: arc haversine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>ahvcos</b></font>: arc havercosine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>ahcvsin</b></font>: arc hacoversine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>ahcvcos</b></font>: arc hacovercosine function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>aexsec</b></font>: arc exsecant function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>aexcsc</b></font>: arc excosecant function.<br><br><br>"

                
                + "<font  face='arial'><font color='blue'><center><b><u>Other Functions: f(z)</u></b></center></font><br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>exp</b></font>: exp function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>log</b></font>: natural logarithm function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>log10</b></font>: base 10 logarithm function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>log2</b></font>: base 2 logarithm function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>sqrt</b></font>: square root function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>abs</b></font>: absolute value function (applied both on real and imaginary parts).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>absre</b></font>: absolute value function (applied only on real part).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>absim</b></font>: absolute value function (applied only on imaginary part).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>conj</b></font>: conjugate number function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>re</b></font>: real part function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>im</b></font>: imaginary part function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>norm</b></font>: euclidean norm function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>arg</b></font>: argument function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>gamma</b></font>: gamma function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>fact</b></font>: factorial function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>erf</b></font>: error function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>rzeta</b></font>: riemann zeta function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>gi</b></font>: gaussian integer function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>rec</b></font>: reciprocal function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>flip</b></font>: flip real to imaginary function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>round</b></font>: math round function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>ceil</b></font>: math ceil function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>floor</b></font>: math floor function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>trunc</b></font>: math truncate function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>deta</b></font>: dirichlet eta function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f1</b></font>: user function f1 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f2</b></font>: user function f2 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f3</b></font>: user function f3 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f4</b></font>: user function f4 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f5</b></font>: user function f5 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f6</b></font>: user function f6 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f7</b></font>: user function f7 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f8</b></font>: user function f8 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f9</b></font>: user function f9 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f10</b></font>: user function f10 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f11</b></font>: user function f11 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f12</b></font>: user function f12 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f13</b></font>: user function f13 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f14</b></font>: user function f14 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f15</b></font>: user function f15 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f16</b></font>: user function f16 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f17</b></font>: user function f17 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f18</b></font>: user function f18 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f19</b></font>: user function f19 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f20</b></font>: user function f20 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f21</b></font>: user function f21 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f22</b></font>: user function f22 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f23</b></font>: user function f23 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f24</b></font>: user function f24 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f25</b></font>: user function f25 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f26</b></font>: user function f26 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f27</b></font>: user function f27 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f28</b></font>: user function f28 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f29</b></font>: user function f29 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f30</b></font>: user function f30 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f31</b></font>: user function f31 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f32</b></font>: user function f32 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f33</b></font>: user function f33 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f34</b></font>: user function f34 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f35</b></font>: user function f35 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f36</b></font>: user function f36 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f37</b></font>: user function f37 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f38</b></font>: user function f38 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f39</b></font>: user function f39 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>f40</b></font>: user function f40 which can be changed in UserDefinedFunctions.java (Compilation is required).<br><br>"
                + "The f1 - f40 functions are focused on experienced users<br>"
                + "that might have some computer science background.<br><br><br>"
                
                + "<font  face='arial'><font color='blue'><center><b><u>Two Argument Functions: f(z, w)</u></b></center></font><br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>logn</b></font>: log base n (argument 1: z, argument 2: base).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>bipol</b></font>: bipolar function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>ibipol</b></font>: inversed bipolar function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>inflect</b></font>: inflection function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>foldu</b></font>: fold up function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>foldd</b></font>: fold down function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>foldl</b></font>: fold left function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>foldr</b></font>: fold right function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>foldi</b></font>: fold in function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>foldo</b></font>: fold out function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>shear</b></font>: shear function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>cmp</b></font>: compare function (returns: -1 when z > w, 1 when z < w, 0 when equal).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>fuzz</b></font>: adds a random pertubation, based on the w argument used.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>normn</b></font>: n-norm function.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>rot</b></font>: a function that rotates in degrees about point zero.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g1</b></font>: user function g1 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g2</b></font>: user function g2 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g3</b></font>: user function g3 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g4</b></font>: user function g4 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g5</b></font>: user function g5 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g6</b></font>: user function g6 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g7</b></font>: user function g7 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g8</b></font>: user function g8 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g9</b></font>: user function g9 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g10</b></font>: user function g10 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g11</b></font>: user function g11 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g12</b></font>: user function g12 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g13</b></font>: user function g13 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g14</b></font>: user function g14 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g15</b></font>: user function g15 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g16</b></font>: user function g16 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g17</b></font>: user function g17 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g18</b></font>: user function g18 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g19</b></font>: user function g19 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g20</b></font>: user function g20 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g21</b></font>: user function g21 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g22</b></font>: user function g22 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g23</b></font>: user function g23 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g24</b></font>: user function g24 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g25</b></font>: user function g25 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g26</b></font>: user function g26 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g27</b></font>: user function g27 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g28</b></font>: user function g28 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g29</b></font>: user function g29 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g30</b></font>: user function g30 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g31</b></font>: user function g31 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g32</b></font>: user function g32 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g33</b></font>: user function g33 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g34</b></font>: user function g34 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g35</b></font>: user function g35 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g36</b></font>: user function g36 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g37</b></font>: user function g37 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g38</b></font>: user function g38 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g39</b></font>: user function g39 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>g40</b></font>: user function g40 which can be changed in UserDefinedFunctions.java (Compilation is required).<br><br>"
                + "The g1 - g40 functions are focused on experienced users<br>"
                + "that might have some computer science background.<br><br><br>"
                
                + "<font  face='arial'><font color='blue'><center><b><u>Multiple Argument User Functions: f(z1, z2, ... z10)</u></b></center></font><br>"
                + "<font  face='arial'>All the following functions can have up to 10 arguments, for example<br>you can use them like this: m1(z, 3+2i) or m2(1+2i, z, c, 3).<br>All the missing arguments will be defaulted to 0.<br><br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m1</b></font>: user function m1 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m2</b></font>: user function m2 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m3</b></font>: user function m3 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m4</b></font>: user function m4 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m5</b></font>: user function m5 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m6</b></font>: user function m6 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m7</b></font>: user function m7 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m8</b></font>: user function m8 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m9</b></font>: user function m9 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m10</b></font>: user function m10 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m11</b></font>: user function m11 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m12</b></font>: user function m12 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m13</b></font>: user function m13 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m14</b></font>: user function m14 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m15</b></font>: user function m15 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m16</b></font>: user function m16 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m17</b></font>: user function m17 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m18</b></font>: user function m18 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m19</b></font>: user function m19 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m20</b></font>: user function m20 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m21</b></font>: user function m21 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m22</b></font>: user function m22 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m23</b></font>: user function m23 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m24</b></font>: user function m24 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m25</b></font>: user function m25 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m26</b></font>: user function m26 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m27</b></font>: user function m27 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m28</b></font>: user function m28 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m29</b></font>: user function m29 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m30</b></font>: user function m30 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m31</b></font>: user function m31 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m32</b></font>: user function m32 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m33</b></font>: user function m33 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m34</b></font>: user function m34 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m35</b></font>: user function m35 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m36</b></font>: user function m36 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m37</b></font>: user function m37 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m38</b></font>: user function m38 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m39</b></font>: user function m39 which can be changed in UserDefinedFunctions.java (Compilation is required).<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>m40</b></font>: user function m40 which can be changed in UserDefinedFunctions.java (Compilation is required).<br><br>"
                + "The m1 - m40 functions are focused on experienced users<br>"
                + "that might have some computer science background.<br><br><br>"
                
                + "<font  face='arial'><font color='blue'><center><b><u>Additional Two Argument Functions: f(z, w)</u></b></center></font><br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>add</b></font>: addition.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>sub</b></font>: subtraction.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>mult</b></font>: multiplication.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>div</b></font>: division.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>rem</b></font>: remainder.<br>"
                + "<font  face='arial'><font size='5' face='arial'>&#8226;</font><font color='red'><b>pow</b></font>: exponentiation.<br><br><br>"
                + "<font  face='arial'><font color='blue'><center><b><u>General Guidelines:</u></b></center></font><br>"
                + "If you set the User Out Coloring or User In Coloring algorithm to the value of -maxn,<br>"
                + "then the corresponding color for Distance Estimation will be used.<br><br>"
                + "If you set the User Out Coloring or User In Coloring algorithm to a negative value,<br>"
                + "then the corresponding color for Special Color will be used."
                

                + "</font>";
        textArea.setText(overview);

        Object[] message = {
            scroll_pane_2,};

        textArea.setCaretPosition(0);

        JOptionPane.showMessageDialog(scroll_pane, message, "User Formulas Help", JOptionPane.QUESTION_MESSAGE);
        main_panel.repaint();
    }
    
}
